### ISSUE TITLE
Investigate if we can use e.g. a Node.js script to update mediaqueries.scss with all SCSS mediaquery mixins

### ISSUE THREAD

**Issue by eriklindebratt** [doberman/dbrmn-scss-framework#6]
It would be really cool if mediaqueries.scss would automatically update when a new file gets added.

We could e.g. have a Node.js script listen to file changes and when a file that has a mediaquery mixin (e.g. `@mixin header-small`) gets added/changed, mediaqueries.scss gets updated with all the new mediaquery mixins from all files that have them.

What do you think?

**Comment by larsericsson** [comment]
Fixed in [https://github.com/doberman/dbrmn-scss-framework/pull/12](https://github.com/doberman/dbrmn-scss-framework/pull/12)
