### ISSUE TITLE
Add CONTRIBUTING.md with info about how to contribute

### ISSUE THREAD

**Issue by eriklindebratt** [doberman/dbrmn-scss-framework#7]
Something similar to [this](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)? We could make it a base for all of our open source projects.

**Comment by larsericsson** [comment]
Fixed [here](https://github.com/doberman/dbrmn-scss-framework/commit/006e361a1e1d326814d6659406d7a7b310236037).
